/* Auto-generated by genmsg_cpp for file /home/robotics/groovy_workspace/sandbox/neato_mudd/msg/LaserRangeData.msg */
#ifndef NEATO_MUDD_MESSAGE_LASERRANGEDATA_H
#define NEATO_MUDD_MESSAGE_LASERRANGEDATA_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"

namespace neato_mudd
{
template <class ContainerAllocator>
struct LaserRangeData_ {
  typedef LaserRangeData_<ContainerAllocator> Type;

  LaserRangeData_()
  : header()
  , range_data()
  {
    range_data.assign(0.0);
  }

  LaserRangeData_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , range_data()
  {
    range_data.assign(0.0);
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef boost::array<float, 360>  _range_data_type;
  boost::array<float, 360>  range_data;


  typedef boost::shared_ptr< ::neato_mudd::LaserRangeData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::neato_mudd::LaserRangeData_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct LaserRangeData
typedef  ::neato_mudd::LaserRangeData_<std::allocator<void> > LaserRangeData;

typedef boost::shared_ptr< ::neato_mudd::LaserRangeData> LaserRangeDataPtr;
typedef boost::shared_ptr< ::neato_mudd::LaserRangeData const> LaserRangeDataConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::neato_mudd::LaserRangeData_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::neato_mudd::LaserRangeData_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace neato_mudd

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::neato_mudd::LaserRangeData_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::neato_mudd::LaserRangeData_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::neato_mudd::LaserRangeData_<ContainerAllocator> > {
  static const char* value() 
  {
    return "4fb78c54e462111a8ca2b51642b46488";
  }

  static const char* value(const  ::neato_mudd::LaserRangeData_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x4fb78c54e462111aULL;
  static const uint64_t static_value2 = 0x8ca2b51642b46488ULL;
};

template<class ContainerAllocator>
struct DataType< ::neato_mudd::LaserRangeData_<ContainerAllocator> > {
  static const char* value() 
  {
    return "neato_mudd/LaserRangeData";
  }

  static const char* value(const  ::neato_mudd::LaserRangeData_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::neato_mudd::LaserRangeData_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
float32[360] range_data\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::neato_mudd::LaserRangeData_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::neato_mudd::LaserRangeData_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::neato_mudd::LaserRangeData_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::neato_mudd::LaserRangeData_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.range_data);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct LaserRangeData_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::neato_mudd::LaserRangeData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::neato_mudd::LaserRangeData_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "range_data[]" << std::endl;
    for (size_t i = 0; i < v.range_data.size(); ++i)
    {
      s << indent << "  range_data[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.range_data[i]);
    }
  }
};


} // namespace message_operations
} // namespace ros

#endif // NEATO_MUDD_MESSAGE_LASERRANGEDATA_H

