/* Auto-generated by genmsg_cpp for file /home/robotics/groovy_workspace/sandbox/neato_mudd/srv/PlaySound.srv */
#ifndef NEATO_MUDD_SERVICE_PLAYSOUND_H
#define NEATO_MUDD_SERVICE_PLAYSOUND_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "ros/service_traits.h"




namespace neato_mudd
{
template <class ContainerAllocator>
struct PlaySoundRequest_ {
  typedef PlaySoundRequest_<ContainerAllocator> Type;

  PlaySoundRequest_()
  : num(0)
  {
  }

  PlaySoundRequest_(const ContainerAllocator& _alloc)
  : num(0)
  {
  }

  typedef int16_t _num_type;
  int16_t num;


  typedef boost::shared_ptr< ::neato_mudd::PlaySoundRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::neato_mudd::PlaySoundRequest_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct PlaySoundRequest
typedef  ::neato_mudd::PlaySoundRequest_<std::allocator<void> > PlaySoundRequest;

typedef boost::shared_ptr< ::neato_mudd::PlaySoundRequest> PlaySoundRequestPtr;
typedef boost::shared_ptr< ::neato_mudd::PlaySoundRequest const> PlaySoundRequestConstPtr;


template <class ContainerAllocator>
struct PlaySoundResponse_ {
  typedef PlaySoundResponse_<ContainerAllocator> Type;

  PlaySoundResponse_()
  : success(false)
  {
  }

  PlaySoundResponse_(const ContainerAllocator& _alloc)
  : success(false)
  {
  }

  typedef uint8_t _success_type;
  uint8_t success;


  typedef boost::shared_ptr< ::neato_mudd::PlaySoundResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::neato_mudd::PlaySoundResponse_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct PlaySoundResponse
typedef  ::neato_mudd::PlaySoundResponse_<std::allocator<void> > PlaySoundResponse;

typedef boost::shared_ptr< ::neato_mudd::PlaySoundResponse> PlaySoundResponsePtr;
typedef boost::shared_ptr< ::neato_mudd::PlaySoundResponse const> PlaySoundResponseConstPtr;

struct PlaySound
{

typedef PlaySoundRequest Request;
typedef PlaySoundResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct PlaySound
} // namespace neato_mudd

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::neato_mudd::PlaySoundRequest_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::neato_mudd::PlaySoundRequest_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::neato_mudd::PlaySoundRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "79e2a05b252e69632375170571b25d3d";
  }

  static const char* value(const  ::neato_mudd::PlaySoundRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x79e2a05b252e6963ULL;
  static const uint64_t static_value2 = 0x2375170571b25d3dULL;
};

template<class ContainerAllocator>
struct DataType< ::neato_mudd::PlaySoundRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "neato_mudd/PlaySoundRequest";
  }

  static const char* value(const  ::neato_mudd::PlaySoundRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::neato_mudd::PlaySoundRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "int16 num\n\
\n\
";
  }

  static const char* value(const  ::neato_mudd::PlaySoundRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::neato_mudd::PlaySoundRequest_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::neato_mudd::PlaySoundResponse_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::neato_mudd::PlaySoundResponse_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::neato_mudd::PlaySoundResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const  ::neato_mudd::PlaySoundResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::neato_mudd::PlaySoundResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "neato_mudd/PlaySoundResponse";
  }

  static const char* value(const  ::neato_mudd::PlaySoundResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::neato_mudd::PlaySoundResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "bool success\n\
\n\
\n\
";
  }

  static const char* value(const  ::neato_mudd::PlaySoundResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::neato_mudd::PlaySoundResponse_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::neato_mudd::PlaySoundRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.num);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct PlaySoundRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::neato_mudd::PlaySoundResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.success);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct PlaySoundResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<neato_mudd::PlaySound> {
  static const char* value() 
  {
    return "b6b3b805312bdb3b12a4c8cc137ba6be";
  }

  static const char* value(const neato_mudd::PlaySound&) { return value(); } 
};

template<>
struct DataType<neato_mudd::PlaySound> {
  static const char* value() 
  {
    return "neato_mudd/PlaySound";
  }

  static const char* value(const neato_mudd::PlaySound&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<neato_mudd::PlaySoundRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "b6b3b805312bdb3b12a4c8cc137ba6be";
  }

  static const char* value(const neato_mudd::PlaySoundRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<neato_mudd::PlaySoundRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "neato_mudd/PlaySound";
  }

  static const char* value(const neato_mudd::PlaySoundRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<neato_mudd::PlaySoundResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "b6b3b805312bdb3b12a4c8cc137ba6be";
  }

  static const char* value(const neato_mudd::PlaySoundResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<neato_mudd::PlaySoundResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "neato_mudd/PlaySound";
  }

  static const char* value(const neato_mudd::PlaySoundResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // NEATO_MUDD_SERVICE_PLAYSOUND_H

