/* Auto-generated by genmsg_cpp for file /home/robot/rosbots/hmc-robot-drivers/missile_launcher/srv/PanRight.srv */
#ifndef MISSILE_LAUNCHER_SERVICE_PANRIGHT_H
#define MISSILE_LAUNCHER_SERVICE_PANRIGHT_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "ros/service_traits.h"




namespace missile_launcher
{
template <class ContainerAllocator>
struct PanRightRequest_ {
  typedef PanRightRequest_<ContainerAllocator> Type;

  PanRightRequest_()
  {
  }

  PanRightRequest_(const ContainerAllocator& _alloc)
  {
  }


  typedef boost::shared_ptr< ::missile_launcher::PanRightRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::missile_launcher::PanRightRequest_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct PanRightRequest
typedef  ::missile_launcher::PanRightRequest_<std::allocator<void> > PanRightRequest;

typedef boost::shared_ptr< ::missile_launcher::PanRightRequest> PanRightRequestPtr;
typedef boost::shared_ptr< ::missile_launcher::PanRightRequest const> PanRightRequestConstPtr;


template <class ContainerAllocator>
struct PanRightResponse_ {
  typedef PanRightResponse_<ContainerAllocator> Type;

  PanRightResponse_()
  : success(false)
  {
  }

  PanRightResponse_(const ContainerAllocator& _alloc)
  : success(false)
  {
  }

  typedef uint8_t _success_type;
  uint8_t success;


  typedef boost::shared_ptr< ::missile_launcher::PanRightResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::missile_launcher::PanRightResponse_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct PanRightResponse
typedef  ::missile_launcher::PanRightResponse_<std::allocator<void> > PanRightResponse;

typedef boost::shared_ptr< ::missile_launcher::PanRightResponse> PanRightResponsePtr;
typedef boost::shared_ptr< ::missile_launcher::PanRightResponse const> PanRightResponseConstPtr;

struct PanRight
{

typedef PanRightRequest Request;
typedef PanRightResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct PanRight
} // namespace missile_launcher

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::missile_launcher::PanRightRequest_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::missile_launcher::PanRightRequest_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::missile_launcher::PanRightRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const  ::missile_launcher::PanRightRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::missile_launcher::PanRightRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "missile_launcher/PanRightRequest";
  }

  static const char* value(const  ::missile_launcher::PanRightRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::missile_launcher::PanRightRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "\n\
";
  }

  static const char* value(const  ::missile_launcher::PanRightRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::missile_launcher::PanRightRequest_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::missile_launcher::PanRightResponse_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::missile_launcher::PanRightResponse_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::missile_launcher::PanRightResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const  ::missile_launcher::PanRightResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::missile_launcher::PanRightResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "missile_launcher/PanRightResponse";
  }

  static const char* value(const  ::missile_launcher::PanRightResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::missile_launcher::PanRightResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "bool success\n\
\n\
\n\
";
  }

  static const char* value(const  ::missile_launcher::PanRightResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::missile_launcher::PanRightResponse_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::missile_launcher::PanRightRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct PanRightRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::missile_launcher::PanRightResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.success);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct PanRightResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<missile_launcher::PanRight> {
  static const char* value() 
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const missile_launcher::PanRight&) { return value(); } 
};

template<>
struct DataType<missile_launcher::PanRight> {
  static const char* value() 
  {
    return "missile_launcher/PanRight";
  }

  static const char* value(const missile_launcher::PanRight&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<missile_launcher::PanRightRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const missile_launcher::PanRightRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<missile_launcher::PanRightRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "missile_launcher/PanRight";
  }

  static const char* value(const missile_launcher::PanRightRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<missile_launcher::PanRightResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const missile_launcher::PanRightResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<missile_launcher::PanRightResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "missile_launcher/PanRight";
  }

  static const char* value(const missile_launcher::PanRightResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // MISSILE_LAUNCHER_SERVICE_PANRIGHT_H

