/* Auto-generated by genmsg_cpp for file /home/robotics/rosbots/hmc-robot-drivers/neato_mudd/msg/NeatoOdom.msg */
#ifndef NEATO_MUDD_MESSAGE_NEATOODOM_H
#define NEATO_MUDD_MESSAGE_NEATOODOM_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"

namespace neato_mudd
{
template <class ContainerAllocator>
struct NeatoOdom_ {
  typedef NeatoOdom_<ContainerAllocator> Type;

  NeatoOdom_()
  : header()
  , x(0.0)
  , y(0.0)
  , theta(0.0)
  {
  }

  NeatoOdom_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , x(0.0)
  , y(0.0)
  , theta(0.0)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef float _x_type;
  float x;

  typedef float _y_type;
  float y;

  typedef float _theta_type;
  float theta;


  typedef boost::shared_ptr< ::neato_mudd::NeatoOdom_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::neato_mudd::NeatoOdom_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct NeatoOdom
typedef  ::neato_mudd::NeatoOdom_<std::allocator<void> > NeatoOdom;

typedef boost::shared_ptr< ::neato_mudd::NeatoOdom> NeatoOdomPtr;
typedef boost::shared_ptr< ::neato_mudd::NeatoOdom const> NeatoOdomConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::neato_mudd::NeatoOdom_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::neato_mudd::NeatoOdom_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace neato_mudd

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::neato_mudd::NeatoOdom_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::neato_mudd::NeatoOdom_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::neato_mudd::NeatoOdom_<ContainerAllocator> > {
  static const char* value() 
  {
    return "4f56726d50ba8b23f7292bbcdc628375";
  }

  static const char* value(const  ::neato_mudd::NeatoOdom_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x4f56726d50ba8b23ULL;
  static const uint64_t static_value2 = 0xf7292bbcdc628375ULL;
};

template<class ContainerAllocator>
struct DataType< ::neato_mudd::NeatoOdom_<ContainerAllocator> > {
  static const char* value() 
  {
    return "neato_mudd/NeatoOdom";
  }

  static const char* value(const  ::neato_mudd::NeatoOdom_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::neato_mudd::NeatoOdom_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
float32 x\n\
float32 y\n\
float32 theta\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::neato_mudd::NeatoOdom_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::neato_mudd::NeatoOdom_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::neato_mudd::NeatoOdom_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::neato_mudd::NeatoOdom_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.x);
    stream.next(m.y);
    stream.next(m.theta);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct NeatoOdom_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::neato_mudd::NeatoOdom_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::neato_mudd::NeatoOdom_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "theta: ";
    Printer<float>::stream(s, indent + "  ", v.theta);
  }
};


} // namespace message_operations
} // namespace ros

#endif // NEATO_MUDD_MESSAGE_NEATOODOM_H

