/* Auto-generated by genmsg_cpp for file /home/robotics/ros_workspace/hmc-robot-drivers/irobot_mudd/srv/Circle.srv */
#ifndef IROBOT_MUDD_SERVICE_CIRCLE_H
#define IROBOT_MUDD_SERVICE_CIRCLE_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "ros/service_traits.h"




namespace irobot_mudd
{
template <class ContainerAllocator>
struct CircleRequest_ {
  typedef CircleRequest_<ContainerAllocator> Type;

  CircleRequest_()
  : speed(0)
  , radius(0)
  {
  }

  CircleRequest_(const ContainerAllocator& _alloc)
  : speed(0)
  , radius(0)
  {
  }

  typedef int16_t _speed_type;
  int16_t speed;

  typedef int16_t _radius_type;
  int16_t radius;


private:
  static const char* __s_getDataType_() { return "irobot_mudd/CircleRequest"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "ef9a01183a8cd54f529667d6e9bf9e4c"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getServerMD5Sum_() { return "7ada5548d47348ecdfb4dedc0f9f402e"; }
public:
  ROS_DEPRECATED static const std::string __s_getServerMD5Sum() { return __s_getServerMD5Sum_(); }

  ROS_DEPRECATED const std::string __getServerMD5Sum() const { return __s_getServerMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "int16 speed\n\
int16 radius\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, speed);
    ros::serialization::serialize(stream, radius);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, speed);
    ros::serialization::deserialize(stream, radius);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(speed);
    size += ros::serialization::serializationLength(radius);
    return size;
  }

  typedef boost::shared_ptr< ::irobot_mudd::CircleRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::irobot_mudd::CircleRequest_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct CircleRequest
typedef  ::irobot_mudd::CircleRequest_<std::allocator<void> > CircleRequest;

typedef boost::shared_ptr< ::irobot_mudd::CircleRequest> CircleRequestPtr;
typedef boost::shared_ptr< ::irobot_mudd::CircleRequest const> CircleRequestConstPtr;


template <class ContainerAllocator>
struct CircleResponse_ {
  typedef CircleResponse_<ContainerAllocator> Type;

  CircleResponse_()
  : success(false)
  {
  }

  CircleResponse_(const ContainerAllocator& _alloc)
  : success(false)
  {
  }

  typedef uint8_t _success_type;
  uint8_t success;


private:
  static const char* __s_getDataType_() { return "irobot_mudd/CircleResponse"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "358e233cde0c8a8bcfea4ce193f8fc15"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getServerMD5Sum_() { return "7ada5548d47348ecdfb4dedc0f9f402e"; }
public:
  ROS_DEPRECATED static const std::string __s_getServerMD5Sum() { return __s_getServerMD5Sum_(); }

  ROS_DEPRECATED const std::string __getServerMD5Sum() const { return __s_getServerMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "bool success\n\
\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, success);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, success);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(success);
    return size;
  }

  typedef boost::shared_ptr< ::irobot_mudd::CircleResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::irobot_mudd::CircleResponse_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct CircleResponse
typedef  ::irobot_mudd::CircleResponse_<std::allocator<void> > CircleResponse;

typedef boost::shared_ptr< ::irobot_mudd::CircleResponse> CircleResponsePtr;
typedef boost::shared_ptr< ::irobot_mudd::CircleResponse const> CircleResponseConstPtr;

struct Circle
{

typedef CircleRequest Request;
typedef CircleResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct Circle
} // namespace irobot_mudd

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::irobot_mudd::CircleRequest_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::irobot_mudd::CircleRequest_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::irobot_mudd::CircleRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "ef9a01183a8cd54f529667d6e9bf9e4c";
  }

  static const char* value(const  ::irobot_mudd::CircleRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xef9a01183a8cd54fULL;
  static const uint64_t static_value2 = 0x529667d6e9bf9e4cULL;
};

template<class ContainerAllocator>
struct DataType< ::irobot_mudd::CircleRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "irobot_mudd/CircleRequest";
  }

  static const char* value(const  ::irobot_mudd::CircleRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::irobot_mudd::CircleRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "int16 speed\n\
int16 radius\n\
\n\
";
  }

  static const char* value(const  ::irobot_mudd::CircleRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::irobot_mudd::CircleRequest_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::irobot_mudd::CircleResponse_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::irobot_mudd::CircleResponse_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::irobot_mudd::CircleResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const  ::irobot_mudd::CircleResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::irobot_mudd::CircleResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "irobot_mudd/CircleResponse";
  }

  static const char* value(const  ::irobot_mudd::CircleResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::irobot_mudd::CircleResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "bool success\n\
\n\
\n\
";
  }

  static const char* value(const  ::irobot_mudd::CircleResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::irobot_mudd::CircleResponse_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::irobot_mudd::CircleRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.speed);
    stream.next(m.radius);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct CircleRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::irobot_mudd::CircleResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.success);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct CircleResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<irobot_mudd::Circle> {
  static const char* value() 
  {
    return "7ada5548d47348ecdfb4dedc0f9f402e";
  }

  static const char* value(const irobot_mudd::Circle&) { return value(); } 
};

template<>
struct DataType<irobot_mudd::Circle> {
  static const char* value() 
  {
    return "irobot_mudd/Circle";
  }

  static const char* value(const irobot_mudd::Circle&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<irobot_mudd::CircleRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "7ada5548d47348ecdfb4dedc0f9f402e";
  }

  static const char* value(const irobot_mudd::CircleRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<irobot_mudd::CircleRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "irobot_mudd/Circle";
  }

  static const char* value(const irobot_mudd::CircleRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<irobot_mudd::CircleResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "7ada5548d47348ecdfb4dedc0f9f402e";
  }

  static const char* value(const irobot_mudd::CircleResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<irobot_mudd::CircleResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "irobot_mudd/Circle";
  }

  static const char* value(const irobot_mudd::CircleResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // IROBOT_MUDD_SERVICE_CIRCLE_H

