/* Auto-generated by genmsg_cpp for file /home/robotics/ros_workspace/hmc-robot-drivers/irobot_mudd/srv/Demo.srv */
#ifndef IROBOT_MUDD_SERVICE_DEMO_H
#define IROBOT_MUDD_SERVICE_DEMO_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "ros/service_traits.h"




namespace irobot_mudd
{
template <class ContainerAllocator>
struct DemoRequest_ {
  typedef DemoRequest_<ContainerAllocator> Type;

  DemoRequest_()
  : demo(0)
  {
  }

  DemoRequest_(const ContainerAllocator& _alloc)
  : demo(0)
  {
  }

  typedef uint8_t _demo_type;
  uint8_t demo;


private:
  static const char* __s_getDataType_() { return "irobot_mudd/DemoRequest"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "38cce318410d78a3661e585adc1dbcfa"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getServerMD5Sum_() { return "ba6bc2ba3d93bab324b9d12a59c0df25"; }
public:
  ROS_DEPRECATED static const std::string __s_getServerMD5Sum() { return __s_getServerMD5Sum_(); }

  ROS_DEPRECATED const std::string __getServerMD5Sum() const { return __s_getServerMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "uint8 demo\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, demo);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, demo);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(demo);
    return size;
  }

  typedef boost::shared_ptr< ::irobot_mudd::DemoRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::irobot_mudd::DemoRequest_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct DemoRequest
typedef  ::irobot_mudd::DemoRequest_<std::allocator<void> > DemoRequest;

typedef boost::shared_ptr< ::irobot_mudd::DemoRequest> DemoRequestPtr;
typedef boost::shared_ptr< ::irobot_mudd::DemoRequest const> DemoRequestConstPtr;


template <class ContainerAllocator>
struct DemoResponse_ {
  typedef DemoResponse_<ContainerAllocator> Type;

  DemoResponse_()
  : success(false)
  {
  }

  DemoResponse_(const ContainerAllocator& _alloc)
  : success(false)
  {
  }

  typedef uint8_t _success_type;
  uint8_t success;


private:
  static const char* __s_getDataType_() { return "irobot_mudd/DemoResponse"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "358e233cde0c8a8bcfea4ce193f8fc15"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getServerMD5Sum_() { return "ba6bc2ba3d93bab324b9d12a59c0df25"; }
public:
  ROS_DEPRECATED static const std::string __s_getServerMD5Sum() { return __s_getServerMD5Sum_(); }

  ROS_DEPRECATED const std::string __getServerMD5Sum() const { return __s_getServerMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "bool success\n\
\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, success);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, success);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(success);
    return size;
  }

  typedef boost::shared_ptr< ::irobot_mudd::DemoResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::irobot_mudd::DemoResponse_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct DemoResponse
typedef  ::irobot_mudd::DemoResponse_<std::allocator<void> > DemoResponse;

typedef boost::shared_ptr< ::irobot_mudd::DemoResponse> DemoResponsePtr;
typedef boost::shared_ptr< ::irobot_mudd::DemoResponse const> DemoResponseConstPtr;

struct Demo
{

typedef DemoRequest Request;
typedef DemoResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct Demo
} // namespace irobot_mudd

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::irobot_mudd::DemoRequest_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::irobot_mudd::DemoRequest_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::irobot_mudd::DemoRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "38cce318410d78a3661e585adc1dbcfa";
  }

  static const char* value(const  ::irobot_mudd::DemoRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x38cce318410d78a3ULL;
  static const uint64_t static_value2 = 0x661e585adc1dbcfaULL;
};

template<class ContainerAllocator>
struct DataType< ::irobot_mudd::DemoRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "irobot_mudd/DemoRequest";
  }

  static const char* value(const  ::irobot_mudd::DemoRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::irobot_mudd::DemoRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "uint8 demo\n\
\n\
";
  }

  static const char* value(const  ::irobot_mudd::DemoRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::irobot_mudd::DemoRequest_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::irobot_mudd::DemoResponse_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::irobot_mudd::DemoResponse_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::irobot_mudd::DemoResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const  ::irobot_mudd::DemoResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::irobot_mudd::DemoResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "irobot_mudd/DemoResponse";
  }

  static const char* value(const  ::irobot_mudd::DemoResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::irobot_mudd::DemoResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "bool success\n\
\n\
\n\
";
  }

  static const char* value(const  ::irobot_mudd::DemoResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::irobot_mudd::DemoResponse_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::irobot_mudd::DemoRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.demo);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct DemoRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::irobot_mudd::DemoResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.success);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct DemoResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<irobot_mudd::Demo> {
  static const char* value() 
  {
    return "ba6bc2ba3d93bab324b9d12a59c0df25";
  }

  static const char* value(const irobot_mudd::Demo&) { return value(); } 
};

template<>
struct DataType<irobot_mudd::Demo> {
  static const char* value() 
  {
    return "irobot_mudd/Demo";
  }

  static const char* value(const irobot_mudd::Demo&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<irobot_mudd::DemoRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "ba6bc2ba3d93bab324b9d12a59c0df25";
  }

  static const char* value(const irobot_mudd::DemoRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<irobot_mudd::DemoRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "irobot_mudd/Demo";
  }

  static const char* value(const irobot_mudd::DemoRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<irobot_mudd::DemoResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "ba6bc2ba3d93bab324b9d12a59c0df25";
  }

  static const char* value(const irobot_mudd::DemoResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<irobot_mudd::DemoResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "irobot_mudd/Demo";
  }

  static const char* value(const irobot_mudd::DemoResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // IROBOT_MUDD_SERVICE_DEMO_H

