/* Auto-generated by genmsg_cpp for file /home/robotics/ros_workspace/hmc-robot-drivers/irobot_mudd/srv/Reset.srv */
#ifndef IROBOT_MUDD_SERVICE_RESET_H
#define IROBOT_MUDD_SERVICE_RESET_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "ros/service_traits.h"




namespace irobot_mudd
{
template <class ContainerAllocator>
struct ResetRequest_ {
  typedef ResetRequest_<ContainerAllocator> Type;

  ResetRequest_()
  : reset(false)
  {
  }

  ResetRequest_(const ContainerAllocator& _alloc)
  : reset(false)
  {
  }

  typedef uint8_t _reset_type;
  uint8_t reset;


private:
  static const char* __s_getDataType_() { return "irobot_mudd/ResetRequest"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "ba4b0b221fb425ac5eaf73f71ae34971"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getServerMD5Sum_() { return "5644e4245ad58afb0dde7f0251867310"; }
public:
  ROS_DEPRECATED static const std::string __s_getServerMD5Sum() { return __s_getServerMD5Sum_(); }

  ROS_DEPRECATED const std::string __getServerMD5Sum() const { return __s_getServerMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "bool reset\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, reset);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, reset);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(reset);
    return size;
  }

  typedef boost::shared_ptr< ::irobot_mudd::ResetRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::irobot_mudd::ResetRequest_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct ResetRequest
typedef  ::irobot_mudd::ResetRequest_<std::allocator<void> > ResetRequest;

typedef boost::shared_ptr< ::irobot_mudd::ResetRequest> ResetRequestPtr;
typedef boost::shared_ptr< ::irobot_mudd::ResetRequest const> ResetRequestConstPtr;


template <class ContainerAllocator>
struct ResetResponse_ {
  typedef ResetResponse_<ContainerAllocator> Type;

  ResetResponse_()
  : success(false)
  {
  }

  ResetResponse_(const ContainerAllocator& _alloc)
  : success(false)
  {
  }

  typedef uint8_t _success_type;
  uint8_t success;


private:
  static const char* __s_getDataType_() { return "irobot_mudd/ResetResponse"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "358e233cde0c8a8bcfea4ce193f8fc15"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getServerMD5Sum_() { return "5644e4245ad58afb0dde7f0251867310"; }
public:
  ROS_DEPRECATED static const std::string __s_getServerMD5Sum() { return __s_getServerMD5Sum_(); }

  ROS_DEPRECATED const std::string __getServerMD5Sum() const { return __s_getServerMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "bool success\n\
\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, success);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, success);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(success);
    return size;
  }

  typedef boost::shared_ptr< ::irobot_mudd::ResetResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::irobot_mudd::ResetResponse_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct ResetResponse
typedef  ::irobot_mudd::ResetResponse_<std::allocator<void> > ResetResponse;

typedef boost::shared_ptr< ::irobot_mudd::ResetResponse> ResetResponsePtr;
typedef boost::shared_ptr< ::irobot_mudd::ResetResponse const> ResetResponseConstPtr;

struct Reset
{

typedef ResetRequest Request;
typedef ResetResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct Reset
} // namespace irobot_mudd

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::irobot_mudd::ResetRequest_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::irobot_mudd::ResetRequest_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::irobot_mudd::ResetRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "ba4b0b221fb425ac5eaf73f71ae34971";
  }

  static const char* value(const  ::irobot_mudd::ResetRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xba4b0b221fb425acULL;
  static const uint64_t static_value2 = 0x5eaf73f71ae34971ULL;
};

template<class ContainerAllocator>
struct DataType< ::irobot_mudd::ResetRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "irobot_mudd/ResetRequest";
  }

  static const char* value(const  ::irobot_mudd::ResetRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::irobot_mudd::ResetRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "bool reset\n\
\n\
";
  }

  static const char* value(const  ::irobot_mudd::ResetRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::irobot_mudd::ResetRequest_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::irobot_mudd::ResetResponse_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::irobot_mudd::ResetResponse_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::irobot_mudd::ResetResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const  ::irobot_mudd::ResetResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::irobot_mudd::ResetResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "irobot_mudd/ResetResponse";
  }

  static const char* value(const  ::irobot_mudd::ResetResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::irobot_mudd::ResetResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "bool success\n\
\n\
\n\
";
  }

  static const char* value(const  ::irobot_mudd::ResetResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::irobot_mudd::ResetResponse_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::irobot_mudd::ResetRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.reset);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct ResetRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::irobot_mudd::ResetResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.success);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct ResetResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<irobot_mudd::Reset> {
  static const char* value() 
  {
    return "5644e4245ad58afb0dde7f0251867310";
  }

  static const char* value(const irobot_mudd::Reset&) { return value(); } 
};

template<>
struct DataType<irobot_mudd::Reset> {
  static const char* value() 
  {
    return "irobot_mudd/Reset";
  }

  static const char* value(const irobot_mudd::Reset&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<irobot_mudd::ResetRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "5644e4245ad58afb0dde7f0251867310";
  }

  static const char* value(const irobot_mudd::ResetRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<irobot_mudd::ResetRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "irobot_mudd/Reset";
  }

  static const char* value(const irobot_mudd::ResetRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<irobot_mudd::ResetResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "5644e4245ad58afb0dde7f0251867310";
  }

  static const char* value(const irobot_mudd::ResetResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<irobot_mudd::ResetResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "irobot_mudd/Reset";
  }

  static const char* value(const irobot_mudd::ResetResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // IROBOT_MUDD_SERVICE_RESET_H

