/* Auto-generated by genmsg_cpp for file /home/robotics/ros_workspace/hmc-robot-drivers/neato_mudd/srv/Exit.srv */
#ifndef NEATO_MUDD_SERVICE_EXIT_H
#define NEATO_MUDD_SERVICE_EXIT_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "ros/service_traits.h"




namespace neato_mudd
{
template <class ContainerAllocator>
struct ExitRequest_ {
  typedef ExitRequest_<ContainerAllocator> Type;

  ExitRequest_()
  {
  }

  ExitRequest_(const ContainerAllocator& _alloc)
  {
  }


  typedef boost::shared_ptr< ::neato_mudd::ExitRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::neato_mudd::ExitRequest_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct ExitRequest
typedef  ::neato_mudd::ExitRequest_<std::allocator<void> > ExitRequest;

typedef boost::shared_ptr< ::neato_mudd::ExitRequest> ExitRequestPtr;
typedef boost::shared_ptr< ::neato_mudd::ExitRequest const> ExitRequestConstPtr;


template <class ContainerAllocator>
struct ExitResponse_ {
  typedef ExitResponse_<ContainerAllocator> Type;

  ExitResponse_()
  : success(false)
  {
  }

  ExitResponse_(const ContainerAllocator& _alloc)
  : success(false)
  {
  }

  typedef uint8_t _success_type;
  uint8_t success;


  typedef boost::shared_ptr< ::neato_mudd::ExitResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::neato_mudd::ExitResponse_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct ExitResponse
typedef  ::neato_mudd::ExitResponse_<std::allocator<void> > ExitResponse;

typedef boost::shared_ptr< ::neato_mudd::ExitResponse> ExitResponsePtr;
typedef boost::shared_ptr< ::neato_mudd::ExitResponse const> ExitResponseConstPtr;

struct Exit
{

typedef ExitRequest Request;
typedef ExitResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct Exit
} // namespace neato_mudd

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::neato_mudd::ExitRequest_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::neato_mudd::ExitRequest_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::neato_mudd::ExitRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const  ::neato_mudd::ExitRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::neato_mudd::ExitRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "neato_mudd/ExitRequest";
  }

  static const char* value(const  ::neato_mudd::ExitRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::neato_mudd::ExitRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "\n\
";
  }

  static const char* value(const  ::neato_mudd::ExitRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::neato_mudd::ExitRequest_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::neato_mudd::ExitResponse_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::neato_mudd::ExitResponse_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::neato_mudd::ExitResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const  ::neato_mudd::ExitResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::neato_mudd::ExitResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "neato_mudd/ExitResponse";
  }

  static const char* value(const  ::neato_mudd::ExitResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::neato_mudd::ExitResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "bool success\n\
\n\
\n\
";
  }

  static const char* value(const  ::neato_mudd::ExitResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::neato_mudd::ExitResponse_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::neato_mudd::ExitRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct ExitRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::neato_mudd::ExitResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.success);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct ExitResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<neato_mudd::Exit> {
  static const char* value() 
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const neato_mudd::Exit&) { return value(); } 
};

template<>
struct DataType<neato_mudd::Exit> {
  static const char* value() 
  {
    return "neato_mudd/Exit";
  }

  static const char* value(const neato_mudd::Exit&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<neato_mudd::ExitRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const neato_mudd::ExitRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<neato_mudd::ExitRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "neato_mudd/Exit";
  }

  static const char* value(const neato_mudd::ExitRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<neato_mudd::ExitResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const neato_mudd::ExitResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<neato_mudd::ExitResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "neato_mudd/Exit";
  }

  static const char* value(const neato_mudd::ExitResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // NEATO_MUDD_SERVICE_EXIT_H

