/* Auto-generated by genmsg_cpp for file /home/robotics/ros_workspace/hmc-robot-drivers/neato_mudd/srv/GetButtons.srv */
#ifndef NEATO_MUDD_SERVICE_GETBUTTONS_H
#define NEATO_MUDD_SERVICE_GETBUTTONS_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "ros/service_traits.h"




namespace neato_mudd
{
template <class ContainerAllocator>
struct GetButtonsRequest_ {
  typedef GetButtonsRequest_<ContainerAllocator> Type;

  GetButtonsRequest_()
  {
  }

  GetButtonsRequest_(const ContainerAllocator& _alloc)
  {
  }


  typedef boost::shared_ptr< ::neato_mudd::GetButtonsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::neato_mudd::GetButtonsRequest_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct GetButtonsRequest
typedef  ::neato_mudd::GetButtonsRequest_<std::allocator<void> > GetButtonsRequest;

typedef boost::shared_ptr< ::neato_mudd::GetButtonsRequest> GetButtonsRequestPtr;
typedef boost::shared_ptr< ::neato_mudd::GetButtonsRequest const> GetButtonsRequestConstPtr;


template <class ContainerAllocator>
struct GetButtonsResponse_ {
  typedef GetButtonsResponse_<ContainerAllocator> Type;

  GetButtonsResponse_()
  : success(false)
  {
  }

  GetButtonsResponse_(const ContainerAllocator& _alloc)
  : success(false)
  {
  }

  typedef uint8_t _success_type;
  uint8_t success;


  typedef boost::shared_ptr< ::neato_mudd::GetButtonsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::neato_mudd::GetButtonsResponse_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct GetButtonsResponse
typedef  ::neato_mudd::GetButtonsResponse_<std::allocator<void> > GetButtonsResponse;

typedef boost::shared_ptr< ::neato_mudd::GetButtonsResponse> GetButtonsResponsePtr;
typedef boost::shared_ptr< ::neato_mudd::GetButtonsResponse const> GetButtonsResponseConstPtr;

struct GetButtons
{

typedef GetButtonsRequest Request;
typedef GetButtonsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct GetButtons
} // namespace neato_mudd

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::neato_mudd::GetButtonsRequest_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::neato_mudd::GetButtonsRequest_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::neato_mudd::GetButtonsRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const  ::neato_mudd::GetButtonsRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::neato_mudd::GetButtonsRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "neato_mudd/GetButtonsRequest";
  }

  static const char* value(const  ::neato_mudd::GetButtonsRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::neato_mudd::GetButtonsRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "\n\
";
  }

  static const char* value(const  ::neato_mudd::GetButtonsRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::neato_mudd::GetButtonsRequest_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::neato_mudd::GetButtonsResponse_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::neato_mudd::GetButtonsResponse_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::neato_mudd::GetButtonsResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const  ::neato_mudd::GetButtonsResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::neato_mudd::GetButtonsResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "neato_mudd/GetButtonsResponse";
  }

  static const char* value(const  ::neato_mudd::GetButtonsResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::neato_mudd::GetButtonsResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "bool success\n\
\n\
\n\
";
  }

  static const char* value(const  ::neato_mudd::GetButtonsResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::neato_mudd::GetButtonsResponse_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::neato_mudd::GetButtonsRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct GetButtonsRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::neato_mudd::GetButtonsResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.success);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct GetButtonsResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<neato_mudd::GetButtons> {
  static const char* value() 
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const neato_mudd::GetButtons&) { return value(); } 
};

template<>
struct DataType<neato_mudd::GetButtons> {
  static const char* value() 
  {
    return "neato_mudd/GetButtons";
  }

  static const char* value(const neato_mudd::GetButtons&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<neato_mudd::GetButtonsRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const neato_mudd::GetButtonsRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<neato_mudd::GetButtonsRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "neato_mudd/GetButtons";
  }

  static const char* value(const neato_mudd::GetButtonsRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<neato_mudd::GetButtonsResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const neato_mudd::GetButtonsResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<neato_mudd::GetButtonsResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "neato_mudd/GetButtons";
  }

  static const char* value(const neato_mudd::GetButtonsResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // NEATO_MUDD_SERVICE_GETBUTTONS_H

