/* Auto-generated by genmsg_cpp for file /home/robotics/ros_workspace/hmc-robot-drivers/neato_mudd/srv/Start.srv */
#ifndef NEATO_MUDD_SERVICE_START_H
#define NEATO_MUDD_SERVICE_START_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "ros/service_traits.h"




namespace neato_mudd
{
template <class ContainerAllocator>
struct StartRequest_ {
  typedef StartRequest_<ContainerAllocator> Type;

  StartRequest_()
  {
  }

  StartRequest_(const ContainerAllocator& _alloc)
  {
  }


  typedef boost::shared_ptr< ::neato_mudd::StartRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::neato_mudd::StartRequest_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct StartRequest
typedef  ::neato_mudd::StartRequest_<std::allocator<void> > StartRequest;

typedef boost::shared_ptr< ::neato_mudd::StartRequest> StartRequestPtr;
typedef boost::shared_ptr< ::neato_mudd::StartRequest const> StartRequestConstPtr;


template <class ContainerAllocator>
struct StartResponse_ {
  typedef StartResponse_<ContainerAllocator> Type;

  StartResponse_()
  : success(false)
  {
  }

  StartResponse_(const ContainerAllocator& _alloc)
  : success(false)
  {
  }

  typedef uint8_t _success_type;
  uint8_t success;


  typedef boost::shared_ptr< ::neato_mudd::StartResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::neato_mudd::StartResponse_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct StartResponse
typedef  ::neato_mudd::StartResponse_<std::allocator<void> > StartResponse;

typedef boost::shared_ptr< ::neato_mudd::StartResponse> StartResponsePtr;
typedef boost::shared_ptr< ::neato_mudd::StartResponse const> StartResponseConstPtr;

struct Start
{

typedef StartRequest Request;
typedef StartResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct Start
} // namespace neato_mudd

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::neato_mudd::StartRequest_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::neato_mudd::StartRequest_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::neato_mudd::StartRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const  ::neato_mudd::StartRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::neato_mudd::StartRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "neato_mudd/StartRequest";
  }

  static const char* value(const  ::neato_mudd::StartRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::neato_mudd::StartRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "\n\
";
  }

  static const char* value(const  ::neato_mudd::StartRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::neato_mudd::StartRequest_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::neato_mudd::StartResponse_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::neato_mudd::StartResponse_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::neato_mudd::StartResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const  ::neato_mudd::StartResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::neato_mudd::StartResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "neato_mudd/StartResponse";
  }

  static const char* value(const  ::neato_mudd::StartResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::neato_mudd::StartResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "bool success\n\
\n\
\n\
";
  }

  static const char* value(const  ::neato_mudd::StartResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::neato_mudd::StartResponse_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::neato_mudd::StartRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct StartRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::neato_mudd::StartResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.success);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct StartResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<neato_mudd::Start> {
  static const char* value() 
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const neato_mudd::Start&) { return value(); } 
};

template<>
struct DataType<neato_mudd::Start> {
  static const char* value() 
  {
    return "neato_mudd/Start";
  }

  static const char* value(const neato_mudd::Start&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<neato_mudd::StartRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const neato_mudd::StartRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<neato_mudd::StartRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "neato_mudd/Start";
  }

  static const char* value(const neato_mudd::StartRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<neato_mudd::StartResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const neato_mudd::StartResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<neato_mudd::StartResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "neato_mudd/Start";
  }

  static const char* value(const neato_mudd::StartResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // NEATO_MUDD_SERVICE_START_H

